version: '3.8'

services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: cardviewer-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
      - SESSION_SECRET=${SESSION_SECRET:-change-this-secret-key}
      - DATABASE_PATH=/app/data/cards.db
      - UPLOAD_DIR=/app/uploads
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:3000}
      - CORS_ORIGINS=${CORS_ORIGINS:-}
    ports:
      - "5001:5001"
    volumes:
      - backend_data:/app/data
      - backend_uploads:/app/uploads
    networks:
      - cardviewer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-}
    container_name: cardviewer-frontend
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-}
    ports:
      - "3001:80"
    depends_on:
      - backend
    networks:
      - cardviewer-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cardviewer-network:
    driver: bridge

volumes:
  backend_data:
    driver: local
  backend_uploads:
    driver: local